name: Deploy front angular

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SSH_KEY_PATH: ${{ github.workspace }}/.ssh/deploy_key

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Prepare SSH Key
        run: |
          mkdir -p ${{ github.workspace }}/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > $SSH_KEY_PATH
          chmod 600 $SSH_KEY_PATH
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ${{ github.workspace }}/.ssh/known_hosts

      - name: Clean remote directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key_path: ${{ env.SSH_KEY_PATH }}
          script: rm -rf /var/www/talenthub/talentFront/dist/browser/*

      - name: Deploy files via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key_path: ${{ env.SSH_KEY_PATH }}
          source: "dist/talent-hub/browser/*"
          target: "/var/www/talenthub/talentFront/dist/browser"

      - name: Fix permissions
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key_path: ${{ env.SSH_KEY_PATH }}
          script: |
            sudo chown -R apache:apache /var/www/talenthub/talentFront
            sudo find /var/www/talenthub/talentFront -type d -exec chmod 755 {} \;
            sudo find /var/www/talenthub/talentFront -type f -exec chmod 644 {} \;
