name: Deploy front angular

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: verificar secretos
        run: | 
            echo "SERVER_HOST: ${{ secrets.SERVER_HOST }}"
            echo "SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}"
            echo "SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}"

      - name: Debug Secrets (solo nombres, no valores)
        run: |
          echo "✅ Verificando que existan secrets..."
          echo "SERVER_HOST: ${{ secrets.SERVER_HOST && '✅ OK' || '❌ FALTA' }}"
          echo "SERVER_USERNAME: ${{ secrets.SERVER_USERNAME && '✅ OK' || '❌ FALTA' }}"
          echo "SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY && '✅ OK' || '❌ FALTA' }}"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build --if-present

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          debug: true
          script: |
            echo "✅ Conexión SSH exitosa"
            rm -rf /var/www/talenthub/talentFront/dist/browser/*
            echo "✅ Carpeta remota limpiada"
