name: Deploy Angular App to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular project
        run: npm run build --if-present

      - name: Clean remote directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf /var/www/talenthub/talentFront/dist/browser/*
            echo "✅ Carpeta remota limpiada"

      - name: Upload build files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/browser/*"
          target: "/var/www/talenthub/talentFront/dist/browser"
          overwrite: true
          strip_components: 0

      - name: Fix permissions
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo chown -R apache:apache /var/www/talenthub/talentFront
            sudo find /var/www/talenthub/talentFront -type d -exec chmod 755 {} \;
            sudo find /var/www/talenthub/talentFront -type f -exec chmod 644 {} \;
            echo "✅ Permisos corregidos"
