name: Deploy front angular
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Clonar repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instalar Node
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # Compilar Angular
      - name: Build Angular app
        run: npm run build -- --configuration production

      # Crear known_hosts
      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      # Limpiar carpeta destino ANTES de copiar
      - name: Clean remote directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf /var/www/talenthub/talentFront/dist/browser/*

      # Subir archivos compilados
      - name: Deploy to server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/talent-hub/browser/*"
          target: "/var/www/talenthub/talentFront/dist/browser"
          strip_components: 0
          overwrite: true

      # Asignar permisos correctos para Apache
      - name: Fix permissions
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo chown -R apache:apache /var/www/talenthub/talentFront
            sudo find /var/www/talenthub/talentFront -type d -exec chmod 755 {} \;
            sudo find /var/www/talenthub/talentFront -type f -exec chmod 644 {} \;
