name: Deploy Front Angular

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Verificar existencia de secretos
      - name: Debug Secrets (solo existencia, no valores)
        run: |
          echo "Verificando que existan secrets..."
          echo "SERVER_HOST: ${{ secrets.SERVER_HOST && 'OK' || ' FALTA' }}"
          echo "SERVER_USERNAME: ${{ secrets.SERVER_USERNAME && 'OK' || ' FALTA' }}"
          echo "SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY && ' OK' || 'FALTA' }}"

      # 3️⃣ Crear archivo de clave SSH temporal
      - name: Crear archivo de clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/temp_key
          sed -i 's/\\n/\n/g' ~/.ssh/temp_key
          chmod 600 ~/.ssh/temp_key
          echo "Clave SSH creada"

      # 4️⃣ Agregar host a known_hosts
      - name: Add host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts 2>/dev/null
          echo "✅ Host agregado a known_hosts"

      # 5️⃣ Probar conexión SSH
      - name: Test SSH Connection
        run: |
          echo "🔹 Probando conexión SSH..."
          ssh -i ~/.ssh/temp_key -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "echo '✅ SSH OK' && whoami"

      # 6️⃣ Configurar Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 7️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 8️⃣ Construir Angular App
      - name: Build Angular App
        run: npm run build -- --configuration production

      # 9️⃣ Verificar que dist se creó
      - name: Verify dist folder
        run: |
          echo " Contenido de dist/:"
          ls -la dist/
          echo " Tamaño:"
          du -sh dist/
          if [ ! -d "dist" ]; then
            echo " ERROR: Carpeta dist no existe"
            exit 1
          fi
          echo " Carpeta dist verificada"

      # 🔟 Subir archivos via SCP
      - name: Upload files via SCP
        run: |
          echo " Subiendo archivos a servidor..."
          scp -i ~/.ssh/temp_key -r -o StrictHostKeyChecking=no dist/talent-hub/browser/* \
            ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/var/www/talenthub/talentFront/dist/browser/
          echo "Archivos subidos exitosamente"

      # 1️⃣1️⃣ Limpiar y reorganizar en servidor
      - name: Cleanup and verify on server
        run: |
          ssh -i ~/.ssh/temp_key -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
          set -e
          
          echo "🔧 Limpiando servidor..."
          
          # Verificar que los archivos se subieron
          if [ ! -f "/var/www/talenthub/talentFront/dist/browser/index.html" ]; then
            echo "ERROR: index.html no encontrado en servidor"
            ls -la /var/www/talenthub/talentFront/dist/browser/
            exit 1
          fi
          
          echo " index.html encontrado"
          
          # Mostrar archivos subidos
          echo " Archivos en servidor:"
          ls -la /var/www/talenthub/talentFront/dist/browser/ | head -15
          
          # Actualizar permisos
          sudo chown -R apache:apache /var/www/talenthub/talentFront/dist/
          sudo chmod -R 755 /var/www/talenthub/talentFront/dist/
          
          echo " Permisos actualizados"
          
          # Recargar Apache
          sudo systemctl reload httpd || sudo systemctl restart httpd
          
          echo "Apache recargado"
          
          EOF

      # 1️⃣2️⃣ Health check
      - name: Health Check
        run: |
          echo "Verificando que la app está disponible..."
          sleep 3
          
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.SERVER_HOST }}/)
          
          echo "HTTP Status: $HTTP_CODE"
          
          if [ "$HTTP_CODE" = "200" ]; then
            echo "Deploy completado exitosamente"
          else
            echo "Código HTTP: $HTTP_CODE"
          fi

      # 1️⃣3️⃣ Limpiar clave SSH
      - name: Cleanup SSH key
        if: always()
        run: |
          rm -f ~/.ssh/temp_key
          echo " Clave SSH eliminada"