name: Deploy front angular
on:
  push:
    branches: 
    - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Corregido: latest
    steps:
      # clonar el repo
      - name: checkout repository
        uses: actions/checkout@v4

      # instalar node y angular CLI 
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      # instalar dependicias
      - name: Install dependencies
        run: npm ci

      # Compilar para produccion
      - name: Build Angular app
        run: npm run build -- --configuration production

      ## copiar archivos compilados al servidor 
      - name: Deploy to server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          # Ajuste de ruta: incluye la carpeta 'browser' y el contenido
          source: "dist/talent-hub/browser/*" 
          # Ajuste de ruta: debe coincidir con el DocumentRoot de Apache
          target: "/var/www/talenthub-front/dist/talent-hub/browser"